import pandas as pd
import os

# --- Configuration ---
# The input file is the sorted CSV generated by token_counter.py
INPUT_CSV_FILE = "tokenized_summary.csv"
# The output file will contain only the task IDs, one per line
OUTPUT_TXT_FILE = "sorted_task_ids.txt"

# --- Execution ---

try:
    # 1. Load the sorted CSV file
    print(f"Reading sorted data from '{INPUT_CSV_FILE}'...")
    df = pd.read_csv(INPUT_CSV_FILE)

    # Ensure the required column is present
    if "task_id" not in df.columns:
        raise ValueError(f"Input CSV must contain a 'task_id' column. Found: {df.columns.tolist()}")

    # 2. Extract the task_id column
    # The data is already sorted from the previous script
    task_ids = df['task_id'].astype(str).tolist()

    # 3. Write the IDs to the TXT file, one per line
    print(f"Writing {len(task_ids)} task IDs to '{OUTPUT_TXT_FILE}'...")
    with open(OUTPUT_TXT_FILE, 'w') as f:
        # Join the list of IDs with a newline character and write it to the file
        f.write('\n'.join(task_ids) + '\n')

    print("\nSuccess! The sorted task IDs have been exported.")
    print(f"File '{OUTPUT_TXT_FILE}' created successfully.")
    
except FileNotFoundError:
    print(f"\n--- ERROR ---")
    print(f"Input file '{INPUT_CSV_FILE}' was not found.")
    print("Please ensure you have run 'token_counter.py' successfully first to generate the required input file.")
    print("-------------")
except ValueError as e:
    print(f"\nError: Data validation failed. {e}")
except Exception as e:
    print(f"\nAn unexpected error occurred during processing: {e}")
